# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.walk_cycle.frame dummy
scoreboard objectives add aj.yea.frame dummy