# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:player_display/animations/walk_cycle/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.walk_cycle.frame 1