# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.player_display.root] run return 0
execute on passengers if entity @s[tag=aj.player_display.data] unless data entity @s {data:{rigHash: 'f3d5cd85b5f66589e84b7b316b1b4164d18349709a176869dfe2e35a4422af30'}} on vehicle run function animated_java:player_display/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1