# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.player_display.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.player_display.animation.walk_cycle.playing] run function animated_java:player_display/animations/walk_cycle/zzz/on_tick
execute if entity @s[tag=aj.player_display.animation.yea.playing] run function animated_java:player_display/animations/yea/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~