# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation:[-0.9063f,0.421f,-0.0368f,-0.125f,0.4226f,0.9029f,-0.079f,-4095.25f,0.0f,-0.0872f,-0.9962f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_leg) {transformation:[-0.9397f,-0.3331f,-0.0777f,0.125f,-0.342f,0.9151f,0.2134f,-5119.25f,0.0f,0.2271f,-0.9739f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
