# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation:[-0.9063f,0.4162f,-0.0734f,-0.125f,0.4226f,0.8925f,-0.1574f,-4095.25f,0.0f,-0.1736f,-0.9848f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_leg) {transformation:[-0.9397f,-0.3067f,-0.1513f,0.125f,-0.342f,0.8428f,0.4156f,-5119.25f,0.0f,0.4423f,-0.8969f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
