# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation:[-0.9063f,0.4082f,-0.1094f,-0.125f,0.4226f,0.8754f,-0.2346f,-4095.25f,0.0f,-0.2588f,-0.9659f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_leg) {transformation:[-0.9397f,-0.2644f,-0.217f,0.125f,-0.342f,0.7264f,0.5961f,-5119.25f,0.0f,0.6344f,-0.773f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
