# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation:[-0.9063f,0.3971f,-0.1445f,-0.125f,0.4226f,0.8517f,-0.31f,-4095.25f,0.0f,-0.342f,-0.9397f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_leg) {transformation:[-0.9397f,-0.2082f,-0.2713f,0.125f,-0.342f,0.572f,0.7455f,-5119.25f,0.0f,0.7934f,-0.6088f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
