# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation:[-0.9063f,0.4217f,-0.0276f,-0.125f,0.4226f,0.9044f,-0.0593f,-4095.25f,0.0f,-0.0654f,-0.9979f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_leg) {transformation:[-0.9397f,-0.2904f,-0.1806f,0.125f,-0.342f,0.798f,0.4962f,-5119.25f,0.0f,0.5281f,-0.8492f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
