# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation:[-0.9063f,0.4126f,0.0915f,-0.125f,0.4226f,0.8848f,0.1962f,-4095.25f,0.0f,0.2164f,-0.9763f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_leg) {transformation:[-0.9397f,-0.3354f,-0.0667f,0.125f,-0.342f,0.9216f,0.1833f,-5119.25f,0.0f,0.1951f,-0.9808f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
