# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation:[-0.9063f,0.3705f,0.2033f,-0.125f,0.4226f,0.7946f,0.4359f,-4095.25f,0.0f,0.481f,-0.8767f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_leg) {transformation:[-0.9397f,-0.3375f,0.0557f,0.125f,-0.342f,0.9271f,-0.1531f,-5119.25f,0.0f,-0.1629f,-0.9866f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
