# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation:[-0.9063f,0.2988f,0.2988f,-0.125f,0.4226f,0.6409f,0.6409f,-4095.25f,0.0f,0.7071f,-0.7071f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
$data merge entity $(bone_left_leg) {transformation:[-0.9397f,-0.2962f,0.171f,0.125f,-0.342f,0.8138f,-0.4698f,-5119.25f,0.0f,-0.5f,-0.866f,0.0f,0.0f,0.0f,0.0f,1.0f],start_interpolation:0,interpolation_duration:1}
