# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.player_display.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_display', 'function_path': 'animated_java:player_display/animations/walk_cycle/next_frame'}
execute if score @s aj.walk_cycle.frame matches 41.. run scoreboard players set @s aj.walk_cycle.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.walk_cycle.frame
execute at @s run function animated_java:player_display/animations/walk_cycle/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.walk_cycle.frame 1