# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.player_display.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_display', 'function_path': 'animated_java:player_display/variants/default/apply'}
execute on passengers if entity @s[tag=aj.player_display.bone.head] run function animated_java:player_display/variants/default/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.player_display.bone.right_arm] run function animated_java:player_display/variants/default/zzz/apply_to_bone_right_arm
execute on passengers if entity @s[tag=aj.player_display.bone.left_arm] run function animated_java:player_display/variants/default/zzz/apply_to_bone_left_arm
execute on passengers if entity @s[tag=aj.player_display.bone.right_leg] run function animated_java:player_display/variants/default/zzz/apply_to_bone_right_leg
execute on passengers if entity @s[tag=aj.player_display.bone.left_leg] run function animated_java:player_display/variants/default/zzz/apply_to_bone_left_leg
execute on passengers if entity @s[tag=aj.player_display.bone.torso] run function animated_java:player_display/variants/default/zzz/apply_to_bone_torso
return 1